# Generated by Django 6.0.4 on 2026-05-30 02:16

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[apps.core.models.validar_dni])),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='comuneros/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comunero',
                'verbose_name_plural': 'Comuneros',
                'db_table': 'comunero',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['dni'], name='comunero_dni_b3c83a_idx'), models.Index(fields=['estado'], name='comunero_estado_24c04b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('ALCALDE', 'Alcalde'), ('TENIENTE_ALCALDE', 'Teniente Alcalde'), ('REGIDOR', 'Regidor'), ('SECRETARIO', 'Secretario'), ('FISCAL', 'Fiscal'), ('VOCAL', 'Vocal')], max_length=20, verbose_name='Cargo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('SUSPENDIDO', 'SUSPENDIDO')], default='ACTIVO', max_length=15, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario_registra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoridades_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra')),
                ('comunero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoridades', to='comunidad.comunero', verbose_name='Comunero')),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'db_table': 'autoridad',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['cargo', 'estado'], name='autoridad_cargo_b38eeb_idx')],
            },
        ),
    ]
