# Generated by Django 6.0.4 on 2026-06-10 21:29

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[apps.core.validators.validate_not_empty], verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, validators=[apps.core.validators.validate_not_empty], verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('fecha', models.DateTimeField(db_index=True, verbose_name='Fecha del evento')),
                ('lugar', models.CharField(blank=True, default='', max_length=200, verbose_name='Lugar')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, validators=[apps.core.validators.validate_not_empty], verbose_name='Titulo')),
                ('contenido', models.TextField(validators=[apps.core.validators.validate_not_empty], verbose_name='Contenido')),
                ('resumen', models.TextField(blank=True, default='', verbose_name='Resumen')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de publicacion')),
                ('estado', models.CharField(choices=[('PUBLICADA', 'Publicada'), ('BORRADOR', 'Borrador'), ('ARCHIVADA', 'Archivada')], db_index=True, default='PUBLICADA', max_length=10, verbose_name='Estado')),
                ('vistas', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='content.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'noticia',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('VIDEO', 'Video')], default='IMAGEN', max_length=10, verbose_name='Tipo')),
                ('archivo', models.FileField(upload_to='multimedia/', verbose_name='Archivo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='content.evento', verbose_name='Evento')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='content.noticia', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Multimedias',
                'db_table': 'multimedia',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('OCULTO', 'Oculto'), ('PENDIENTE', 'Pendiente'), ('ELIMINADO', 'Eliminado')], default='PUBLICADO', max_length=10, verbose_name='Estado')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('respuesta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='content.comentario', verbose_name='Respuesta a')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='content.noticia', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['noticia', 'estado'], name='comentario_noticia_d296f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('LOVE', 'Love'), ('ANGRY', 'Angry')], max_length=10, verbose_name='Tipo de reaccion')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reacciones', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='content.noticia', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Reaccion',
                'verbose_name_plural': 'Reacciones',
                'db_table': 'reaccion',
                'ordering': ['-fecha'],
                'unique_together': {('noticia', 'autor')},
            },
        ),
    ]
