# Generated by Django 6.0.4 on 2026-06-11 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaccion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comentario',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='content.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='reaccion',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='content.comentario', verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='reaccion',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='content.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='content.noticia', verbose_name='Noticia'),
        ),
        migrations.AlterField(
            model_name='reaccion',
            name='noticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='content.noticia', verbose_name='Noticia'),
        ),
        migrations.AlterField(
            model_name='reaccion',
            name='tipo',
            field=models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=10, verbose_name='Tipo de reaccion'),
        ),
        migrations.AddConstraint(
            model_name='reaccion',
            constraint=models.UniqueConstraint(condition=models.Q(('noticia__isnull', False)), fields=('noticia', 'autor'), name='uniq_reaccion_noticia_autor'),
        ),
        migrations.AddConstraint(
            model_name='reaccion',
            constraint=models.UniqueConstraint(condition=models.Q(('evento__isnull', False)), fields=('evento', 'autor'), name='uniq_reaccion_evento_autor'),
        ),
        migrations.AddConstraint(
            model_name='reaccion',
            constraint=models.UniqueConstraint(condition=models.Q(('comentario__isnull', False)), fields=('comentario', 'autor'), name='uniq_reaccion_comentario_autor'),
        ),
    ]
