# Generated by Django 6.0.4 on 2026-06-18 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_reaccion_unique_together_comentario_evento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por el usuario')], db_index=True, default='PENDIENTE', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de solicitud')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revision')),
                ('notas_admin', models.TextField(blank=True, default='', verbose_name='Notas del administrador')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_baja_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_baja', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de baja',
                'verbose_name_plural': 'Solicitudes de baja',
                'db_table': 'solicitud_baja',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTICIA', 'Noticia'), ('EVENTO', 'Evento')], db_index=True, max_length=10, verbose_name='Tipo')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha agregado')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='content.evento', verbose_name='Evento')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='content.noticia', verbose_name='Noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favorito',
                'ordering': ['-fecha_agregado'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('noticia__isnull', False)), fields=('usuario', 'noticia'), name='uniq_favorito_usuario_noticia'), models.UniqueConstraint(condition=models.Q(('evento__isnull', False)), fields=('usuario', 'evento'), name='uniq_favorito_usuario_evento')],
            },
        ),
        migrations.CreateModel(
            name='NovedadVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vista', models.DateTimeField(auto_now=True, verbose_name='Fecha de vista')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades_vistas', to='content.evento', verbose_name='Evento')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades_vistas', to='content.noticia', verbose_name='Noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades_vistas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Novedad vista',
                'verbose_name_plural': 'Novedades vistas',
                'db_table': 'novedad_vista',
                'ordering': ['-fecha_vista'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('noticia__isnull', False)), fields=('usuario', 'noticia'), name='uniq_novedad_vista_usuario_noticia'), models.UniqueConstraint(condition=models.Q(('evento__isnull', False)), fields=('usuario', 'evento'), name='uniq_novedad_vista_usuario_evento')],
            },
        ),
    ]
