# Generated by Django 6.0.4 on 2026-06-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_solicitudbaja_favorito_novedadvista'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL de imagen externa'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL de imagen externa'),
        ),
    ]
