# Generated by Django 6.0.4 on 2026-06-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_evento_imagen_url_noticia_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='vistas',
            field=models.PositiveIntegerField(default=0, verbose_name='Vistas'),
        ),
    ]
