# Generated by Django 6.0.4 on 2026-06-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_evento_categoria'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='novedadvista',
            name='uniq_novedad_vista_usuario_noticia',
        ),
        migrations.RemoveConstraint(
            model_name='novedadvista',
            name='uniq_novedad_vista_usuario_evento',
        ),
        migrations.DeleteModel(
            name='NovedadVista',
        ),
    ]
