# Generated by Django 6.0.4 on 2026-06-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_novedadvista_uniq_novedad_vista_usuario_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudbaja',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada por el usuario')], db_index=True, default='PENDIENTE', max_length=12),
        ),
    ]
