# Generated by Django 6.0.4 on 2026-06-19 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='referencia_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de referencia'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='referencia_tipo',
            field=models.CharField(blank=True, choices=[('NOTICIA', 'Noticia'), ('EVENTO', 'Evento'), ('USUARIO', 'Usuario'), ('SOLICITUD_BAJA', 'Solicitud de baja'), ('RECLAMO', 'Reclamo'), ('CONTACTO', 'Contacto'), ('COMENTARIO', 'Comentario')], default='', max_length=20, verbose_name='Tipo de referencia'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url_destino',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL de destino'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario', '-fecha'], name='messaging_n_destina_f80b3d_idx'),
        ),
    ]
