# Generated by Django 6.0.4 on 2026-06-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_notificacion_referencia_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('info', 'Informacion'), ('aprobacion_cuenta', 'Aprobacion de cuenta'), ('rechazo_cuenta', 'Rechazo de cuenta'), ('cuenta_bloqueada', 'Cuenta bloqueada'), ('cuenta_desbloqueada', 'Cuenta desbloqueada'), ('cuenta_inactivada', 'Cuenta inactivada'), ('nueva_noticia', 'Nueva noticia'), ('nuevo_evento', 'Nuevo evento'), ('nueva_solicitud_baja', 'Nueva solicitud de baja'), ('solicitud_baja_aprobada', 'Solicitud de baja aprobada'), ('solicitud_baja_rechazada', 'Solicitud de baja rechazada'), ('solicitud_baja_cancelada', 'Solicitud de baja cancelada'), ('comentario_moderado', 'Comentario moderado'), ('nuevo_mensaje_contacto', 'Nuevo mensaje de contacto'), ('nuevo_reclamo', 'Nuevo reclamo'), ('reclamo_estado_cambiado', 'Reclamo - estado cambiado'), ('mensaje', 'Mensaje interno')], default='info', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='url_destino',
            field=models.URLField(blank=True, default='', max_length=2000, verbose_name='URL de destino'),
        ),
    ]
