"""
MySQL timezone loader: Parse TZif files from tzdata zoneinfo dir and load into mysql.* tables.

This script parses TZif (v2/v3) binary files to extract transition times, UTC offsets,
DST flags, and timezone abbreviation strings. Populates the four MySQL timezone tables:
  time_zone, time_zone_name, time_zone_transition, time_zone_transition_type

Usage: python load_tzdata.py
"""

import os
import sys
import struct
from datetime import datetime, timezone

TZDATA_ZONEINFO = os.path.join(
    os.path.dirname(__import__('tzdata').__file__), 'zoneinfo'
)


def parse_tzif_v2(filepath):
    """Parse v2/v3 TZif file, return list of (timestamp, utoff, dst, abbrev) tuples."""
    with open(filepath, 'rb') as f:
        data = f.read()

    # --- header parsing ---
    def _read_int32(off):
        return struct.unpack_from('>i', data, off)[0]

    def _read_int64(off):
        return struct.unpack_from('>q', data, off)[0]

    magic = data[0:4]
    if magic != b'TZif':
        raise ValueError(f'Not a TZif file: {filepath}')

    version = chr(data[4])

    isutcnt = _read_int32(20)
    isstdcnt = _read_int32(24)
    leapcnt = _read_int32(28)
    timecnt = _read_int32(32)
    typecnt = _read_int32(36)
    charcnt = _read_int32(40)

    off = 44
    # skip v1 transition times
    off += timecnt * 4
    # skip v1 transition type indices
    off += timecnt
    # skip v1 ttinfos
    off += typecnt * 6
    # skip v1 abbrev strings
    off += charcnt
    # skip v1 leap seconds
    off += leapcnt * 8
    # skip v1 std/wall
    off += isstdcnt
    # skip v1 ut/local
    off += isutcnt

    if version in ('2', '3'):
        # skip magic + version + reserved
        off += 4 + 1 + 15
        isutcnt = _read_int32(off + 0)
        isstdcnt = _read_int32(off + 4)
        leapcnt = _read_int32(off + 8)
        timecnt = _read_int32(off + 12)
        typecnt = _read_int32(off + 16)
        charcnt = _read_int32(off + 20)

        off += 24

        # v2 transition times (8 bytes each)
        transitions = []
        for _ in range(timecnt):
            transitions.append(_read_int64(off))
            off += 8

        # transition type indices
        tt_indexes = []
        for _ in range(timecnt):
            tt_indexes.append(data[off])
            off += 1

        # ttinfo structs
        ttinfos = []
        for _ in range(typecnt):
            utoff = _read_int32(off)
            dst = data[off + 4]
            abb_idx = data[off + 5]
            ttinfos.append((utoff, dst, abb_idx))
            off += 6

        # abbreviation strings
        abbr_data = data[off:off + charcnt]
        off += charcnt
        # We ignore the rest (leap seconds, std/wall, ut/local)
    else:
        # v1 only — use 32-bit timestamps
        off = 44
        transitions = []
        for _ in range(timecnt):
            transitions.append(_read_int32(off))
            off += 4

        tt_indexes = []
        for _ in range(timecnt):
            tt_indexes.append(data[off])
            off += 1

        ttinfos = []
        for _ in range(typecnt):
            utoff = _read_int32(off)
            dst = data[off + 4]
            abb_idx = data[off + 5]
            ttinfos.append((utoff, dst, abb_idx))
            off += 6

        abbr_data = data[off:off + charcnt]
        off += charcnt

    def _get_abbr(idx):
        end = abbr_data.find(b'\x00', idx)
        return abbr_data[idx:end].decode('ascii')

    rows = []
    for i, ts in enumerate(transitions):
        tt_idx = tt_indexes[i]
        utoff, dst, abb_idx = ttinfos[tt_idx]
        abbr = _get_abbr(abb_idx)
        rows.append((ts, utoff, dst, abbr))

    return rows


def escape_sql(val):
    if val is None:
        return 'NULL'
    if isinstance(val, bytes):
        return "'" + val.decode('ascii').replace("'", "''") + "'"
    if isinstance(val, str):
        return "'" + val.replace("'", "''") + "'"
    if isinstance(val, bool):
        return '1' if val else '0'
    return str(val)


def main():
    zonefiles = []
    for root, dirs, files in os.walk(TZDATA_ZONEINFO):
        for f in files:
            if f.startswith('.') or f == '__init__.py':
                continue
            full = os.path.join(root, f)
            rel = os.path.relpath(full, TZDATA_ZONEINFO).replace('\\', '/')
            zonefiles.append((rel, full))

    zonefiles.sort()
    print(f'Found {len(zonefiles)} timezone files', file=sys.stderr)

    # We build SQL as a series of INSERT statements
    # Using explicit ID generation (NOT AUTO_INCREMENT) so we can reference IDs

    sql_lines = [
        '-- Generated by load_tzdata.py from tzdata package',
        '-- Truncate existing data',
        'DELETE FROM mysql.time_zone_transition;',
        'DELETE FROM mysql.time_zone_transition_type;',
        'DELETE FROM mysql.time_zone_name;',
        'DELETE FROM mysql.time_zone;',
        '',
        '-- Insert root timezone row',
        'INSERT INTO mysql.time_zone (Time_zone_id, Use_leap_seconds) VALUES (1, \'N\');',
        '',
        '-- Use Etc/UTC as UTC reference',
    ]

    # Reserve time_zone_id 1 for a default placeholder (or we'll use it for UTC)
    # Each region gets a time_zone_id starting from 1
    tzid = 1

    seen_abbrevs = {}

    for name, filepath in zonefiles:
        try:
            rows = parse_tzif_v2(filepath)
        except Exception as e:
            print(f'WARN: skipping {name}: {e}', file=sys.stderr)
            continue

        if not rows:
            # No transitions means it's a fixed-offset zone like Etc/GMT+5
            # We still need at least one transition_type
            pass

        sql_lines.append(f'-- Zone: {name} (tzid={tzid})')

        if rows:
            # Deduplicate ttinfo structures
            ttinfo_map = {}  # (utoff, dst, abbr) -> tt_type_id
            tt_list = []      # ordered list of (utoff, dst, abbr)

            for ts, utoff, dst, abbr in rows:
                key = (utoff, dst, abbr)
                if key not in ttinfo_map:
                    ttid = len(tt_list)
                    ttinfo_map[key] = ttid
                    tt_list.append(key)
                    sql_lines.append(
                        f'INSERT INTO mysql.time_zone_transition_type '
                        f'(Time_zone_id, Transition_type_id, Offset, Is_DST, Abbreviation) '
                        f'VALUES ({tzid}, {ttid}, {utoff}, {dst}, {escape_sql(abbr)});'
                    )

            # Insert transitions
            for ts, utoff, dst, abbr in rows:
                ttid = ttinfo_map[(utoff, dst, abbr)]
                sql_lines.append(
                    f'INSERT INTO mysql.time_zone_transition '
                    f'(Time_zone_id, Transition_time, Transition_type_id) '
                    f'VALUES ({tzid}, {ts}, {ttid});'
                )
        else:
            # Fixed-offset zone: one transition type, no transitions
            is_dst = 0
            if name.startswith('Etc/GMT'):
                # Etc/GMT+5 means UTC-5 in POSIX convention
                try:
                    parts = name.split('Etc/GMT')
                    if parts[1]:
                        val = int(parts[1])
                        offset = -val * 3600
                    else:
                        offset = 0
                except (ValueError, IndexError):
                    offset = 0
                abbr = name.replace('Etc/', '')
            elif name in ('UTC', 'UTC0', 'GMT', 'GMT0', 'GMT-0', 'GMT+0', 'Greenwich', 'Universal', 'Zulu'):
                offset = 0
                abbr = 'UTC'
            else:
                offset = 0
                abbr = name.split('/')[-1][:8] if '/' in name else name[:8]
                # Hardcode some common ones
                known = {
                    'EST': (-18000, 'EST'),
                    'EST5EDT': (-18000, 'EST'),
                    'HST': (-36000, 'HST'),
                    'CST6CDT': (-21600, 'CST'),
                    'MST': (-25200, 'MST'),
                    'MST7MDT': (-25200, 'MST'),
                    'PST8PDT': (-28800, 'PST'),
                }
                if name in known:
                    offset = known[name][0]

            sql_lines.append(
                f'INSERT INTO mysql.time_zone_transition_type '
                f'(Time_zone_id, Transition_type_id, Offset, Is_DST, Abbreviation) '
                f'VALUES ({tzid}, 0, {offset}, {is_dst}, {escape_sql(abbr)});'
            )

        sql_lines.append(f'INSERT INTO mysql.time_zone_name (Name, Time_zone_id) VALUES ({escape_sql(name)}, {tzid});')
        sql_lines.append('')

        tzid += 1

    # Now execute via MySQLdb
    try:
        import MySQLdb
        conn = MySQLdb.connect(
            host='127.0.0.1',
            user='root',
            passwd='',
            db='mysql',
        )
        conn.autocommit = True
        cursor = conn.cursor()

        print('Executing SQL...', file=sys.stderr)

        for line in sql_lines:
            stripped = line.strip()
            if not stripped or stripped.startswith('--'):
                continue
            cursor.execute(stripped)

        cursor.execute('SELECT COUNT(*) FROM mysql.time_zone_name')
        count = cursor.fetchone()[0]
        print(f'Success! Loaded {count} timezone names', file=sys.stderr)

        cursor.close()
        conn.close()
    except ImportError:
        print('MySQLdb not available. SQL dumped to stdout.', file=sys.stderr)
        for line in sql_lines:
            print(line)
    except Exception as e:
        print(f'ERROR: {e}', file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
