# Generated by Django 6.0.4 on 2026-05-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_comentario_options_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='url',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/', verbose_name='Archivo (imagen o video)'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='orden',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
    ]
