# Generated by Django 6.0.4 on 2026-05-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_autoridad_contactomensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroReclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('tipo_solicitud', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('QUEJA', 'Queja'), ('SUGERENCIA', 'Sugerencia')], max_length=15, verbose_name='Tipo de solicitud')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('pedido', models.TextField(blank=True, null=True, verbose_name='Pedido del usuario')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revisión'), ('ATENDIDO', 'Atendido')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Libro de reclamación',
                'verbose_name_plural': 'Libro de reclamaciones',
                'db_table': 'libro_reclamacion',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
