# Generated by Django 6.0.4 on 2026-05-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_libroreclamacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/perfiles/', verbose_name='Foto de perfil'),
        ),
    ]
