# Generated by Django 6.0.4 on 2026-05-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
