# Generated by Django 6.0.4 on 2026-05-31 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_delete_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('PENDIENTE', 'PENDIENTE'), ('RECHAZADO', 'RECHAZADO'), ('ELIMINADO', 'ELIMINADO')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='reaccion',
            name='tipo',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('LOVE', 'LOVE'), ('ANGRY', 'ANGRY')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='reaccion',
            unique_together={('usuario', 'noticia', 'evento')},
        ),
    ]
