# Generated by Django 6.0.4 on 2026-06-17 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidad', '0002_autoridad_activo_autoridad_cargo_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesion'), ('LOGIN_FAILED', 'Login fallido'), ('LOGOUT', 'Cierre de sesion'), ('APPROVE', 'Aprobar usuario'), ('REJECT', 'Rechazar usuario'), ('BLOCK', 'Bloquear usuario'), ('UNBLOCK', 'Desbloquear usuario'), ('PASSWORD_RESET', 'Reset de contrasena'), ('TWO_FA_ENABLE', 'Activar 2FA'), ('TWO_FA_DISABLE', 'Desactivar 2FA'), ('OTP_SENT', 'OTP enviado'), ('OTP_VERIFIED', 'OTP verificado'), ('OTP_FAILED', 'OTP fallido'), ('OTP_EXPIRED', 'OTP expirado')], db_index=True, max_length=24)),
                ('modelo_afectado', models.CharField(blank=True, default='', max_length=100)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=50)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('autoridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to='comunidad.autoridad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='audit_log_usuario_7bea45_idx'), models.Index(fields=['accion', '-timestamp'], name='audit_log_accion_08b597_idx')],
            },
        ),
    ]
