# Generated by Django 6.0.4 on 2026-06-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Inicio de sesion'), ('LOGIN_FAILED', 'Login fallido'), ('LOGOUT', 'Cierre de sesion'), ('APPROVE', 'Aprobar usuario'), ('REJECT', 'Rechazar usuario'), ('BLOCK', 'Bloquear usuario'), ('UNBLOCK', 'Desbloquear usuario'), ('PASSWORD_RESET', 'Reset de contrasena'), ('TWO_FA_ENABLE', 'Activar 2FA'), ('TWO_FA_DISABLE', 'Desactivar 2FA'), ('OTP_SENT', 'OTP enviado'), ('OTP_VERIFIED', 'OTP verificado'), ('OTP_FAILED', 'OTP fallido'), ('OTP_EXPIRED', 'OTP expirado'), ('APPROVE_FAILED', 'Intento de aprobacion fallido'), ('BAJA_REQUESTED', 'Solicitud de baja creada'), ('BAJA_APPROVED', 'Solicitud de baja aprobada'), ('BAJA_REJECTED', 'Solicitud de baja rechazada'), ('BAJA_CANCELLED', 'Solicitud de baja cancelada por el usuario')], db_index=True, max_length=24),
        ),
    ]
