server:
    port: 8080

spring:
    application:
        name: zapotal-gateway

django:
    api:
        url: http://localhost:8000

management:
    endpoints:
        web:
        exposure:
            include: health,info,metrics
    endpoint:
        health:
        show-details: always

logging:
    level:
        root: INFO
        com.comunidad.gateway: INFO