# Generated by Django 6.0.4 on 2026-06-20 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_donante', models.CharField(blank=True, max_length=200, verbose_name='Nombre del donante')),
                ('email_donante', models.EmailField(blank=True, max_length=254, verbose_name='Email del donante')),
                ('documento_donante', models.CharField(blank=True, max_length=20, verbose_name='DNI/RUC del donante')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Monto')),
                ('moneda', models.CharField(default='PEN', max_length=3, verbose_name='Moneda')),
                ('mensaje', models.TextField(blank=True, max_length=500, verbose_name='Mensaje')),
                ('anonima', models.BooleanField(default=False, verbose_name='Donar anonimamente')),
                ('destinatario', models.CharField(choices=[('COMUNIDAD', 'Comunidad general'), ('PROYECTO_OBRAS', 'Obras e infraestructura'), ('PROYECTO_BECAS', 'Becas educativas'), ('PROYECTO_SALUD', 'Programas de salud'), ('PROYECTO_AGRicola', 'Desarrollo agricola'), ('OTRO', 'Otro (especificar en mensaje)')], default='COMUNIDAD', max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de inicio de pago'), ('EN_PROCESO', 'Pago enviado a MP, esperando confirmacion'), ('APROBADO', 'Pago aprobado por MP'), ('RECHAZADO', 'Pago rechazado por MP'), ('REEMBOLSADO', 'Pago reembolsado al donante'), ('CANCELADO', 'Donacion cancelada por el usuario/admin')], db_index=True, default='PENDIENTE', max_length=20)),
                ('estado_detalle', models.TextField(blank=True, verbose_name='Detalle del estado')),
                ('mp_payment_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('mp_status', models.CharField(blank=True, max_length=50)),
                ('mp_status_detail', models.CharField(blank=True, max_length=100)),
                ('mp_payment_method', models.CharField(blank=True, max_length=50, verbose_name='MP payment_method_id')),
                ('mp_payment_type', models.CharField(blank=True, max_length=50, verbose_name='MP payment_type_id')),
                ('mp_installments', models.IntegerField(blank=True, null=True)),
                ('mp_raw_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta cruda de MP')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_at', models.DateTimeField(blank=True, null=True)),
                ('reembolsado_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Null si la donacion es anonima o de visitante no logueado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario donante')),
            ],
            options={
                'verbose_name': 'Donacion',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='don_estado_fecha_idx'), models.Index(fields=['usuario', '-created_at'], name='don_usuario_fecha_idx')],
            },
        ),
    ]
