# Generated by Django 6.0.4 on 2026-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='mp_notification_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='ID de notificacion MP (x-request-id o data.id)'),
        ),
    ]
