# Generated by Django 6.0.4 on 2026-06-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEstatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('HISTORIA', 'Nuestra Historia'), ('MISION', 'Mision'), ('VISION', 'Vision'), ('VALORES', 'Valores'), ('INICIO_HERO', 'Inicio - Hero'), ('INICIO_SUBTITULO', 'Inicio - Subtitulo'), ('CONTACTO_INFO', 'Informacion de contacto'), ('FOOTER', 'Pie de pagina'), ('AUTORIDADES_INTRO', 'Autoridades - Introduccion'), ('DONACIONES_INTRO', 'Donaciones - Introduccion')], db_index=True, max_length=30, unique=True, verbose_name='Seccion')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido (texto plano)')),
                ('contenido_html', models.TextField(blank=True, default='', help_text='HTML enriquecido que se sanitizara en backend antes de servir.', verbose_name='Contenido HTML (opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cms/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Contenido estatico',
                'verbose_name_plural': 'Contenidos estaticos',
                'db_table': 'contenido_estatico',
                'ordering': ['orden', 'seccion'],
            },
        ),
    ]
