# Generated by Django 6.0.4 on 2026-05-30 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_evento', models.DateTimeField(verbose_name='Fecha del evento')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='content.categoria', verbose_name='Categoría')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'evento',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='content.categoria', verbose_name='Categoría')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'noticia',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='multimedia/', verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('IMAGEN', 'IMAGEN'), ('VIDEO', 'VIDEO')], max_length=10, verbose_name='Tipo')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='content.evento', verbose_name='Evento')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='content.noticia', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Multimedia',
                'db_table': 'multimedia',
                'ordering': ['orden', '-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('estado', models.CharField(choices=[('APROBADO', 'APROBADO'), ('PENDIENTE', 'PENDIENTE'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=10)),
                ('tiene_palabras_prohibidas', models.BooleanField(default=False)),
                ('editado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='content.comentario', verbose_name='Comentario padre')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='content.evento', verbose_name='Evento')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='content.noticia', verbose_name='Noticia')),
            ],
            options={
                'db_table': 'comentario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIKE', 'LIKE'), ('LOVE', 'LOVE'), ('ENOJO', 'ENOJO')], max_length=10, verbose_name='Tipo')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='content.evento', verbose_name='Evento')),
                ('noticia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='content.noticia', verbose_name='Noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reacción',
                'verbose_name_plural': 'Reacciones',
                'db_table': 'reaccion',
            },
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['estado', 'fecha_evento'], name='evento_estado_c86239_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-fecha_publicacion'], name='noticia_estado_cf5337_idx'),
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['categoria', 'estado'], name='noticia_categor_42c28d_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['noticia', '-fecha'], name='comentario_noticia_b992ef_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['usuario', '-fecha'], name='comentario_usuario_bfe5ac_idx'),
        ),
    ]
