# Generated by Django 6.0.4 on 2026-06-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='canal_verificacion',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email (Gmail - Resend)'), ('SMS', 'SMS (Firebase)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='facebook_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='failed_otp_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_rechazo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='proveedor_oauth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_OTP', 'Pendiente verificacion OTP'), ('PENDIENTE_APROBACION', 'Pendiente aprobacion admin'), ('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('BLOQUEADO', 'Bloqueado por admin'), ('RECHAZADO', 'Rechazado por admin')], db_index=True, default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_registro', models.JSONField(blank=True, default=dict)),
                ('ip_registro', models.GenericIPAddressField()),
                ('user_agent_registro', models.CharField(blank=True, default='', max_length=255)),
                ('oauth_provider', models.CharField(blank=True, default='', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('notas_admin', models.TextField(blank=True, default='')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobacion pendiente',
                'verbose_name_plural': 'Aprobaciones pendientes',
                'db_table': 'pending_approval',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGISTRO', 'Verificacion de registro'), ('RESET_PASSWORD', 'Reset de contrasena'), ('TWO_FA', 'Verificacion 2FA'), ('CAMBIO_EMAIL', 'Cambio de email'), ('CAMBIO_TELEFONO', 'Cambio de telefono')], max_length=20)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('codigo_hash', models.CharField(max_length=128)),
                ('destinatario', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_verification',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'tipo', '-creado_en'], name='otp_verific_usuario_f3cdda_idx'), models.Index(fields=['expira_en'], name='otp_verific_expira__659afd_idx')],
            },
        ),
    ]
