# Generated by Django 6.0.4 on 2026-06-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_aprobado_por_usuario_canal_verificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='two_factor_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='canal_verificacion',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email (Resend)')], max_length=10, null=True),
        ),
    ]
