# Generated by Django 6.0.4 on 2026-06-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_two_factor_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='facebook_id',
        ),
    ]
