# Generated by Django 6.0.4 on 2026-06-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_usuario_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueo temporal hasta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_OTP', 'Pendiente verificacion OTP'), ('PENDIENTE_APROBACION', 'Pendiente aprobacion admin'), ('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO'), ('BLOQUEADO', 'Bloqueado por admin'), ('RECHAZADO', 'Rechazado por admin'), ('DE_BAJA', 'Cuenta dada de baja (permanente)')], db_index=True, default='ACTIVO', max_length=20, verbose_name='Estado'),
        ),
    ]
