# Generated by Django 6.0.4 on 2026-06-10 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('comunero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autoridad', to='accounts.comunero', verbose_name='Comunero')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autoridad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
