# Generated by Django 6.0.4 on 2026-06-17 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='cargo_tipo',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('REGIDOR', 'Regidor'), ('TESORERO', 'Tesorero'), ('SECRETARIO', 'Secretario'), ('VOCAL', 'Vocal'), ('OTRO', 'Otro')], db_index=True, default='OTRO', help_text='Version normalizada del cargo para el sistema de jerarquia.', max_length=20, verbose_name='Tipo de cargo'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='comunero_info',
            field=models.CharField(blank=True, default='', help_text='Snapshot textual del nombre previo a la migracion.', max_length=200, verbose_name='Comunero (texto legacy)'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='es_admin',
            field=models.BooleanField(default=False, help_text='Solo presidente y cargos con permisos administrativos.', verbose_name='¿Tiene acceso al panel admin?'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='periodo_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin del periodo'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio del periodo'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='reporta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='comunidad.autoridad', verbose_name='Reporta a'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='cargo',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('REGIDOR', 'Regidor'), ('TESORERO', 'Tesorero'), ('SECRETARIO', 'Secretario'), ('VOCAL', 'Vocal'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin (legacy)'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio (legacy)'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='periodo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Periodo'),
        ),
    ]
