# Generated by Django 6.0.4 on 2026-06-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0002_autoridad_activo_autoridad_cargo_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto oficial. Si esta vacia, se usa la foto del usuario asociado.', null=True, upload_to='autoridades/', verbose_name='Foto de la autoridad'),
        ),
    ]
