# Generated by Django 6.0.4 on 2026-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0003_autoridad_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Funciones y responsabilidades del cargo (segun Ley 24656, 27972 o 28440).', verbose_name='Descripcion del cargo'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='dni',
            field=models.CharField(blank=True, default='', help_text='DNI desnormalizado (puede no tener Comunero asociado, ej. Gobernador).', max_length=8, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='duracion_mandato_anos',
            field=models.PositiveSmallIntegerField(default=2, help_text='2 para Comunal, 4 para Municipal, variable para Politico.', verbose_name='Duracion del mandato (anos)'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='email_institucional',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email institucional'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='nivel_gobierno',
            field=models.CharField(choices=[('COMUNAL', 'Directiva Comunal'), ('MUNICIPAL', 'Municipalidad de Centro Poblado'), ('POLITICO', 'Autoridad Politica')], db_index=True, default='COMUNAL', help_text='Nivel al que pertenece la autoridad: Comunal / Municipal / Politico.', max_length=20, verbose_name='Nivel de gobierno'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='nro_partida_sunarp',
            field=models.CharField(blank=True, default='', help_text='Numero de partida registral donde esta inscrita la autoridad.', max_length=50, verbose_name='Partida SUNARP'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Orden dentro del mismo nivel. Presidente=1, Vice=2, etc.', verbose_name='Orden de visualizacion'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='', help_text='Para validar cuota 30% (Ley 30982).', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefono de contacto'),
        ),
    ]
