# Generated by Django 6.0.4 on 2026-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_autoridad_descripcion_autoridad_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='cargo',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('SECRETARIO', 'Secretario'), ('TESORERO', 'Tesorero'), ('FISCAL', 'Fiscal'), ('VOCAL', 'Vocal'), ('REGIDOR', 'Regidor'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='cargo_tipo',
            field=models.CharField(choices=[('PRESIDENTE', 'Presidente'), ('VICEPRESIDENTE', 'Vicepresidente'), ('SECRETARIO', 'Secretario'), ('TESORERO', 'Tesorero'), ('FISCAL', 'Fiscal'), ('VOCAL', 'Vocal'), ('REGIDOR', 'Regidor'), ('OTRO', 'Otro')], db_index=True, default='OTRO', help_text='Version normalizada del cargo para el sistema de jerarquia.', max_length=20, verbose_name='Tipo de cargo'),
        ),
    ]
