# Generated by Django 6.0.4 on 2026-06-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0005_alter_autoridad_cargo_alter_autoridad_cargo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='autoridad_anterior',
            field=models.ForeignKey(blank=True, help_text='Vinculo a la autoridad que precede a esta (en caso de reelecion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reelecciones_sucesivas', to='comunidad.autoridad', verbose_name='Autoridad anterior (periodo previo)'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='es_cargo_tradicional',
            field=models.BooleanField(db_index=True, default=False, help_text='Cargo tradicional andino (Varayoc, Mayordomo, Padrino, etc.).', verbose_name='Es cargo tradicional'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='estado_inscripcion',
            field=models.CharField(blank=True, choices=[('', 'Sin tramite'), ('INSCRITO', 'Inscrito'), ('EN_TRAMITE', 'En tramite'), ('OBSERVADO', 'Observado'), ('PENDIENTE', 'Pendiente'), ('VENCIDO', 'Vencido')], default='', help_text='Estado del tramite ante SUNARP.', max_length=20, verbose_name='Estado de inscripcion'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='fecha_inscripcion',
            field=models.DateField(blank=True, help_text='Fecha en que se inscribio en SUNARP.', null=True, verbose_name='Fecha de inscripcion'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='fecha_vencimiento_inscripcion',
            field=models.DateField(blank=True, help_text='Vencimiento de la vigencia de la partida.', null=True, verbose_name='Vencimiento de vigencia registral'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='lengua_materna',
            field=models.CharField(blank=True, choices=[('', 'No especificado'), ('ES', 'Espanol'), ('QU', 'Quechua (Chinchaysuyo)'), ('AW', 'Awajun'), ('WP', 'Wampis'), ('OT', 'Otro')], default='', help_text='Idioma nativo predominante de la Comunidad (requisito Ley 24656 Art. 20.d).', max_length=2, verbose_name='Lengua materna'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='nombre_tradicional',
            field=models.CharField(blank=True, default='', help_text='Nombre del cargo en idioma nativo o tradicional (ej. "Varayoc", "Alcalde Vara").', max_length=100, verbose_name='Nombre tradicional'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='reelegido',
            field=models.BooleanField(default=False, help_text='Es reelegido por un segundo periodo consecutivo? (max 1 reelecion)', verbose_name='Reelegido'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='resolucion_inscripcion',
            field=models.CharField(blank=True, default='', help_text='Numero de la resolucion regional/ministerial de inscripcion.', max_length=50, verbose_name='Resolucion de inscripcion'),
        ),
        migrations.AddField(
            model_name='autoridad',
            name='sede_inscripcion',
            field=models.CharField(blank=True, default='', help_text='Oficina registral donde se inscribio (ej. Oficina Registral de Jaen).', max_length=100, verbose_name='Oficina registral (SUNARP)'),
        ),
        migrations.CreateModel(
            name='ComiteComunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. "Comite Electoral 2026", "Comite Revisor de Cuentas 2026".', max_length=150, verbose_name='Nombre del comite')),
                ('tipo', models.CharField(choices=[('ELECTORAL', 'Comite Electoral'), ('REVISOR_CUENTAS', 'Comite Revisor de Cuentas'), ('RONDAS', 'Rondas Campesinas'), ('GESTION', 'Comite de Gestion'), ('OBRAS', 'Comite de Obras'), ('EDUCACION', 'Comite de Educacion'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='Tipo de comite')),
                ('nivel', models.CharField(choices=[('COMUNAL', 'Nivel Comunal'), ('ANEXO', 'Anexo/Sector'), ('DISTRITAL', 'Nivel Distrital')], db_index=True, default='COMUNAL', max_length=20, verbose_name='Nivel')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Funciones del comite y marco legal aplicable.', verbose_name='Descripcion / funciones')),
                ('fecha_constitucion', models.DateField(blank=True, help_text='Fecha en que se eligio al comite en Asamblea.', null=True, verbose_name='Fecha de constitucion')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Inicio del periodo')),
                ('periodo_fin', models.DateField(blank=True, null=True, verbose_name='Fin del periodo')),
                ('activo', models.BooleanField(default=True)),
                ('acta_pdf', models.FileField(blank=True, help_text='Acta firmada en formato PDF.', null=True, upload_to='comites/actas/', verbose_name='Acta de constitucion (PDF)')),
                ('presidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comunidad.autoridad', verbose_name='Presidente del comite')),
                ('secretario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comunidad.autoridad', verbose_name='Secretario del comite')),
                ('vocal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='comunidad.autoridad', verbose_name='Vocal del comite')),
            ],
            options={
                'verbose_name': 'Comite Comunal',
                'verbose_name_plural': 'Comites Comunales',
                'ordering': ['-fecha_constitucion', 'tipo'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'periodo_inicio'), name='unique_comite_por_tipo_y_periodo')],
            },
        ),
    ]
