# Generated by Django 6.0.4 on 2026-06-24 21:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0006_autoridad_autoridad_anterior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oficial', models.CharField(default='Comunidad Campesina Niño Dios de Zapotal', max_length=200, verbose_name='Nombre oficial')),
                ('nombre_corto', models.CharField(default='Comunidad Zapotal', max_length=100, verbose_name='Nombre corto')),
                ('eslogan', models.CharField(blank=True, default='', max_length=200, verbose_name='Eslogan')),
                ('descripcion_corta', models.TextField(blank=True, default='', verbose_name='Descripcion corta')),
                ('descripcion_larga', models.TextField(blank=True, default='', verbose_name='Descripcion larga')),
                ('historia_html', models.TextField(blank=True, default='', help_text='Texto largo sobre la historia de la Comunidad.', verbose_name='Historia (HTML/Markdown)')),
                ('mision', models.TextField(blank=True, default='', verbose_name='Mision')),
                ('vision', models.TextField(blank=True, default='', verbose_name='Vision')),
                ('valores', models.JSONField(blank=True, default=list, help_text='Lista de {nombre, descripcion, icono}.', verbose_name='Valores')),
                ('distrito', models.CharField(default='Huarango', max_length=100, verbose_name='Distrito')),
                ('provincia', models.CharField(default='San Ignacio', max_length=100, verbose_name='Provincia')),
                ('region', models.CharField(default='Cajamarca', max_length=100, verbose_name='Region')),
                ('ubigeo', models.CharField(default='060903', max_length=10, verbose_name='Ubigeo')),
                ('direccion_casa_comunal', models.CharField(default='Centro Poblado Zapotal, Distrito Huarango, San Ignacio, Cajamarca', max_length=300, verbose_name='Direccion Casa Comunal')),
                ('coordenadas_lat', models.DecimalField(decimal_places=7, default=-5.3983, max_digits=10, verbose_name='Latitud')),
                ('coordenadas_lng', models.DecimalField(decimal_places=7, default=-78.7055, max_digits=10, verbose_name='Longitud')),
                ('codigo_postal', models.CharField(default='06860', max_length=10, verbose_name='Codigo postal')),
                ('telefono_fijo', models.CharField(blank=True, default='+51 931 757 530', max_length=20, verbose_name='Telefono fijo')),
                ('telefono_emergencias', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono emergencias')),
                ('whatsapp_numero', models.CharField(blank=True, default='', help_text='Ej: +51931757530', max_length=20, verbose_name='WhatsApp (con prefijo pais)')),
                ('email_contacto', models.EmailField(default='contacto@comunidadzapotal.gob.pe', max_length=254, verbose_name='Email de contacto')),
                ('email_privacidad', models.EmailField(default='privacidad@comunidadzapotal.gob.pe', max_length=254, verbose_name='Email privacidad / DPO')),
                ('email_denuncias', models.EmailField(default='denuncias@comunidadzapotal.gob.pe', max_length=254, verbose_name='Email de denuncias')),
                ('horario_atencion', models.CharField(default='Lun a Vie, 8:00 a 17:00', max_length=200, verbose_name='Horario de atencion')),
                ('logo_url', models.URLField(blank=True, default='', verbose_name='Logo URL')),
                ('foto_casa_comunal_url', models.URLField(blank=True, default='', verbose_name='Foto Casa Comunal URL')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Configuracion de la Comunidad',
                'verbose_name_plural': 'Configuracion de la Comunidad',
            },
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Imagen')),
                ('categoria', models.CharField(choices=[('COMUNIDAD', 'Comunidad'), ('AUTORIDADES', 'Autoridades'), ('FESTIVIDADES', 'Festividades'), ('INFRAESTRUCTURA', 'Infraestructura'), ('NATURALEZA', 'Naturaleza'), ('PATRIMONIO', 'Patrimonio Cultural'), ('OTRO', 'Otro')], default='COMUNIDAD', max_length=20, verbose_name='Categoria')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen de Galeria',
                'verbose_name_plural': 'Imagenes de Galeria',
                'ordering': ['orden', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HitoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha exacta')),
                ('anio', models.PositiveIntegerField(blank=True, help_text='Usar cuando no se conoce mes/dia exacto.', null=True, verbose_name='Anio')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hitos/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Hito Historico',
                'verbose_name_plural': 'Hitos Historicos',
                'ordering': ['orden', '-anio', '-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MarcoLegalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('norma', models.CharField(help_text='Ej: Ley 24656 + D.S. 008-91-TR', max_length=200, verbose_name='Norma legal')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('icono', models.CharField(default='FaGavel', help_text='Nombre del icono Fa de react-icons/fa.', max_length=50, verbose_name='Icono (react-icons)')),
                ('url_externa', models.URLField(blank=True, default='', verbose_name='URL externa')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Item de Marco Legal',
                'verbose_name_plural': 'Items de Marco Legal',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User agent')),
                ('leido', models.BooleanField(default=False, verbose_name='Leido')),
                ('respondido', models.BooleanField(default=False, verbose_name='Respondido')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PaginaLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('terminos', 'Terminos y Condiciones'), ('privacidad', 'Politica de Privacidad'), ('cookies', 'Politica de Cookies')], unique=True, verbose_name='Slug')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('resumen_corto', models.TextField(blank=True, default='', verbose_name='Resumen corto')),
                ('contenido', models.TextField(help_text='Texto legal completo de la pagina.', verbose_name='Contenido (HTML/Markdown)')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('fecha_vigencia', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de vigencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Pagina Legal',
                'verbose_name_plural': 'Paginas Legales',
                'ordering': ['slug'],
            },
        ),
    ]
