# Generated by Django 6.0.4 on 2026-06-25 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0007_configuracioncomunidad_galeriaimagen_hitohistorico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='nota_admin',
            field=models.TextField(blank=True, default='', verbose_name='Nota interna del admin'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='nota_admin_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nota interna - fecha'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='nota_admin_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_mensajes_contacto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='respondido_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Respondido en'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='respondido_desde_panel',
            field=models.BooleanField(default=False, verbose_name='Respondido desde el panel'),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_mensajes_contacto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='respondido_texto',
            field=models.TextField(blank=True, default='', verbose_name='Texto de la respuesta enviada'),
        ),
        migrations.AddIndex(
            model_name='mensajecontacto',
            index=models.Index(fields=['leido', '-fecha'], name='comunidad_m_leido_587b92_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajecontacto',
            index=models.Index(fields=['prioridad', '-fecha'], name='comunidad_m_priorid_a3f6e9_idx'),
        ),
    ]
