# Generated by Django 6.0.4 on 2026-06-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0008_mensaje_contacto_campos_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='moderacion_comentarios_previa',
            field=models.BooleanField(default=False, help_text='Si esta activo, los comentarios quedan PENDIENTES hasta aprobacion admin.', verbose_name='Moderacion previa de comentarios'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='modulo_comentarios_activo',
            field=models.BooleanField(default=True, help_text='Permite deshabilitar comentarios en noticias y eventos.', verbose_name='Modulo Comentarios activo'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='modulo_donaciones_activo',
            field=models.BooleanField(default=True, help_text='Permite mostrar/ocultar la seccion de donaciones en el sitio publico.', verbose_name='Modulo Donaciones activo'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='modulo_favoritos_activo',
            field=models.BooleanField(default=True, help_text='Permite mostrar/ocultar el boton de favoritos en noticias/eventos.', verbose_name='Modulo Favoritos activo'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='modulo_registro_abierto',
            field=models.BooleanField(default=True, help_text='Permite bloquear el registro de nuevos usuarios.', verbose_name='Registro publico de usuarios abierto'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='notificaciones_email_activas',
            field=models.BooleanField(default=True, help_text='Envia emails de notificacion al admin (bienvenida, alertas, etc).', verbose_name='Notificaciones por email activas'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='tiempo_sesion_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duracion del access token JWT.', verbose_name='Tiempo de sesion en minutos'),
        ),
    ]
