# Generated by Django 6.0.4 on 2026-06-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0009_configuracioncomunidad_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='conocenos_cta_descripcion',
            field=models.TextField(blank=True, default='', help_text='Si esta vacio, se usa descripcion_corta.', verbose_name='Conocenos: descripcion CTA final'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='conocenos_cta_titulo',
            field=models.CharField(default='Comprometidos con el futuro', max_length=200, verbose_name='Conocenos: titulo CTA final'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='conocenos_etiqueta',
            field=models.CharField(default='Conocenos', max_length=50, verbose_name='Conocenos: etiqueta superior'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='conocenos_hero_subtitulo',
            field=models.TextField(blank=True, default='', help_text='Si esta vacio, se usa eslogan.', verbose_name='Conocenos: subtitulo del hero'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='conocenos_hero_titulo',
            field=models.CharField(default='Una comunidad viva y organizada', max_length=200, verbose_name='Conocenos: titulo del hero'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='conocenos_ubicacion_titulo',
            field=models.CharField(default='Donde estamos', max_length=100, verbose_name='Conocenos: titulo ubicacion'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='galeria_subtitulo',
            field=models.TextField(blank=True, default='', verbose_name='Galeria: subtitulo'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='galeria_titulo',
            field=models.CharField(default='Galeria', max_length=100, verbose_name='Galeria: titulo'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='historia_etiqueta',
            field=models.CharField(default='Origen comunal', max_length=50, verbose_name='Nuestra Historia: etiqueta superior'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='historia_hero_subtitulo',
            field=models.TextField(blank=True, default='', help_text='Si esta vacio, se usa eslogan.', verbose_name='Nuestra Historia: subtitulo del hero'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='historia_hero_titulo',
            field=models.CharField(default='Nuestra historia', max_length=200, verbose_name='Nuestra Historia: titulo del hero'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='historia_seccion_titulo',
            field=models.CharField(default='Raices que fortalecen nuestra identidad', max_length=200, verbose_name='Nuestra Historia: titulo seccion contenido'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='historia_timeline_titulo',
            field=models.CharField(default='Linea de tiempo', max_length=100, verbose_name='Nuestra Historia: titulo timeline'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='marcolocal_subtitulo',
            field=models.TextField(blank=True, default='', help_text='Si esta vacio, usa un texto generico.', verbose_name='Marco Legal: subtitulo'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='marcolocal_titulo',
            field=models.CharField(default='Marco Legal', max_length=100, verbose_name='Marco Legal: titulo'),
        ),
    ]
