# Generated by Django 6.0.4 on 2026-06-29 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0010_configuracioncomunidad_conocenos_cta_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta visible')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripcion')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoria de Galeria',
                'verbose_name_plural': 'Categorias de Galeria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TextoSeccionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identificador unico. Ej: conocenos.hero.titulo', max_length=100, unique=True, verbose_name='Key (slug)')),
                ('seccion', models.CharField(choices=[('CONOCENOS_HERO', 'Conocenos - Hero'), ('CONOCENOS_MV', 'Conocenos - Mision y Vision'), ('CONOCENOS_UBICACION', 'Conocenos - Ubicacion'), ('CONOCENOS_CTA', 'Conocenos - CTA Final'), ('MARCOLOCAL_HERO', 'Marco Legal - Hero'), ('GALERIA_HERO', 'Galeria - Hero'), ('HISTORIA_HERO', 'Nuestra Historia - Hero'), ('HISTORIA_CONTENIDO', 'Nuestra Historia - Contenido'), ('HISTORIA_TIMELINE', 'Nuestra Historia - Timeline')], max_length=30, verbose_name='Seccion')),
                ('tipo', models.CharField(choices=[('TITULO', 'Titulo'), ('SUBTITULO', 'Subtitulo / descripcion'), ('HTML', 'HTML libre'), ('JSON', 'JSON estructurado')], default='TITULO', max_length=20, verbose_name='Tipo de contenido')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Titulo descriptivo (solo admin)')),
                ('contenido', models.TextField(verbose_name='Contenido (texto/HTML/JSON segun tipo)')),
                ('idioma', models.CharField(default='es-PE', max_length=5, verbose_name='Idioma')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textos_seccion_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Texto de Seccion Interna',
                'verbose_name_plural': 'Textos de Secciones Internas',
                'ordering': ['seccion', 'key'],
                'unique_together': {('key', 'idioma')},
            },
        ),
    ]
