# Generated by Django 6.0.4 on 2026-06-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0011_categoriagaleria_textoseccioninterna'),
        ('content', '0006_evento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaimagen',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galeria_imagenes', to='content.evento', verbose_name='Evento asociado'),
        ),
        migrations.AddField(
            model_name='galeriaimagen',
            name='imagen_url_externa',
            field=models.URLField(blank=True, default='', help_text='URL externa (ej. R2/CDN). Si esta vacia, se usa el ImageField local.', verbose_name='Imagen URL externa'),
        ),
        migrations.AddField(
            model_name='galeriaimagen',
            name='noticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galeria_imagenes', to='content.noticia', verbose_name='Noticia asociada'),
        ),
    ]
