# Generated by Django 6.0.4 on 2026-06-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0012_galeriaimagen_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='contacto_casa_comunal_descripcion',
            field=models.TextField(blank=True, default='', help_text='Parrafo que aparece bajo el titulo "Casa Comunal" en /contacto.', verbose_name='Contacto: descripcion Casa Comunal'),
        ),
        migrations.AddField(
            model_name='configuracioncomunidad',
            name='contacto_denuncias_descripcion',
            field=models.TextField(blank=True, default='', help_text='Parrafo que aparece bajo el titulo "Canal de Denuncias" en /contacto.', verbose_name='Contacto: descripcion Canal de Denuncias'),
        ),
        migrations.AlterField(
            model_name='textoseccioninterna',
            name='seccion',
            field=models.CharField(choices=[('CONOCENOS_HERO', 'Conocenos - Hero'), ('CONOCENOS_MV', 'Conocenos - Mision y Vision'), ('CONOCENOS_UBICACION', 'Conocenos - Ubicacion'), ('CONOCENOS_CTA', 'Conocenos - CTA Final'), ('MARCOLOCAL_HERO', 'Marco Legal - Hero'), ('GALERIA_HERO', 'Galeria - Hero'), ('HISTORIA_HERO', 'Nuestra Historia - Hero'), ('HISTORIA_CONTENIDO', 'Nuestra Historia - Contenido'), ('HISTORIA_TIMELINE', 'Nuestra Historia - Timeline'), ('AUTORIDADES_COMITES', 'Autoridades - Comites Especializados')], max_length=30, verbose_name='Seccion'),
        ),
    ]
