# Generated by Django 6.0.4 on 2026-06-30 14:06

from django.db import migrations


def backfill_fecha(apps, schema_editor):
    """Poblar fecha y orden en registros existentes de GaleriaImagen
    que tengan una noticia o evento asociado pero fecha/orden vacios."""
    GaleriaImagen = apps.get_model('comunidad', 'GaleriaImagen')
    for gi in GaleriaImagen.objects.iterator():
        updated = False
        if not gi.fecha:
            if gi.noticia_id:
                gi.fecha = gi.noticia.fecha_publicacion.date()
                updated = True
            elif gi.evento_id:
                gi.fecha = gi.evento.fecha.date()
                updated = True
        if updated:
            gi.save(update_fields=['fecha'])
    # Asignar orden secuencial (1, 2, 3...) basado en fecha + id
    for idx, gi in enumerate(
        GaleriaImagen.objects.order_by('-fecha', 'id').iterator(), start=1
    ):
        GaleriaImagen.objects.filter(pk=gi.pk).update(orden=idx)


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0013_configuracioncomunidad_contacto_casa_comunal_descripcion_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_fecha, migrations.RunPython.noop),
    ]
