# Generated by Django 6.0.4 on 2026-07-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0014_backfill_galeria_fecha_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/', verbose_name='Imagen'),
        ),
    ]
