# Generated by Django 6.0.4 on 2026-06-10 21:29
# Loop 2.1: ContactoMensaje eliminado (codigo muerto). El modelo del libro
# de reclamaciones se mantiene identico al original.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibroReclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='', max_length=15, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, default='', max_length=200, verbose_name='Direccion')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Libro de reclamacion',
                'verbose_name_plural': 'Libro de reclamaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
