# Generated by Django 6.0.4 on 2026-06-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_libro_reclamacion_campos_legales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroreclamacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('VENCIDO', 'Vencido (silencio administrativo)')], default='PENDIENTE', max_length=15, verbose_name='Estado'),
        ),
    ]
